<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopupAlert_Email_harus_diisi</name>
   <tag></tag>
   <elementGuidId>6733c89f-6c42-4e15-b5d0-3ddaa27bfc42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.app-alert.alert.alert-danger.alert-dismissable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a13ff98-63fa-42b1-89aa-900c95c32444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>a8ebbcd4-548e-48f7-96de-9dfeeb7718f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-alert alert alert-danger alert-dismissable</value>
      <webElementGuid>e781f633-cd5c-4736-8103-ec69b4b5b47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Close alertEmail harus diisi.</value>
      <webElementGuid>1a1e6658-ef92-4faf-bda3-fd7129916dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;app-alert alert alert-danger alert-dismissable&quot;]</value>
      <webElementGuid>7fe4a978-07f0-4882-a5d6-e4aab81248c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div</value>
      <webElementGuid>5f7f7545-57bb-4bfc-9555-ea95347a771e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>c2138ece-5910-437d-90c6-9a5c62ff153a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×Close alertEmail harus diisi.' or . = '×Close alertEmail harus diisi.')]</value>
      <webElementGuid>ffa100e7-2d80-4e29-8d75-ba3b9950ccd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
