<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopupAlert_Password_harus_diisi</name>
   <tag></tag>
   <elementGuidId>a4d2bf67-d265-4af1-bdaa-125870dccb43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.app-alert.alert.alert-danger.alert-dismissable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf322618-1d4b-43d6-9266-75ff645f582e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>343249b3-921b-4663-b21b-963de3583eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-alert alert alert-danger alert-dismissable</value>
      <webElementGuid>2275a272-9d8a-4f93-acde-2c45d049419e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Close alertPassword harus diisi.</value>
      <webElementGuid>9b315ae0-7827-41db-8767-26e633e101ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;app-alert alert alert-danger alert-dismissable&quot;]</value>
      <webElementGuid>669dd1d3-7da6-4a3e-b4c7-dd5904bc07ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div</value>
      <webElementGuid>be5060af-3ea6-4698-a1f3-d17da578592b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>0f84ddbf-977a-4870-8130-e647ec7ed948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×Close alertPassword harus diisi.' or . = '×Close alertPassword harus diisi.')]</value>
      <webElementGuid>c7de4924-3143-45b8-bd21-3a68d4ed0e74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
