<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopupAlert_Password-atau-email-anda-salah</name>
   <tag></tag>
   <elementGuidId>6a6c2057-a322-48a2-8c51-52f70e8e3323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.app-alert.alert.alert-danger.alert-dismissable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7cb3d14c-78c2-480d-99b1-0eb93d1b7847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>8a91ade9-c5b1-49a0-a176-a46972ed4b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-alert alert alert-danger alert-dismissable</value>
      <webElementGuid>811e7fc9-a8a8-4b9c-a19a-020a64c39fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×Close alertPassword atau email anda salah.</value>
      <webElementGuid>10770afd-b7cd-4163-9ff8-f865c9aab12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;app-alert alert alert-danger alert-dismissable&quot;]</value>
      <webElementGuid>3a6fc9ad-a06a-4af0-b1b0-b155e0255b03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div</value>
      <webElementGuid>80f03a4f-4c20-4e18-972e-61542915da72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>24a00ad7-9b78-4f60-8ad0-876e855c25a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '×Close alertPassword atau email anda salah.' or . = '×Close alertPassword atau email anda salah.')]</value>
      <webElementGuid>4051046e-a930-44fc-8819-0f8a6f138ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
