<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_In Review</name>
   <tag></tag>
   <elementGuidId>0deb6ba0-0727-4224-b9bf-a5311e055df7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/nav/div/div/ul/li[2]/ul/li/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.metismenu-link.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5aa81fde-f453-40f2-b42f-8f25823355aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>metismenu-link active</value>
      <webElementGuid>c1c5e70f-340d-4ed8-b81b-38c8903ee3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/home/inventory/review</value>
      <webElementGuid>51f93ac7-55b7-410e-aeb2-b3bc01d5d225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In Review</value>
      <webElementGuid>6c68e4d8-25e6-4a8c-96bf-bb6698691f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/nav[@class=&quot;navbar-default navbar-static-side&quot;]/div[@class=&quot;sidebar-collapse&quot;]/div[@class=&quot;metismenu nav&quot;]/ul[@class=&quot;metismenu-container&quot;]/li[@class=&quot;metismenu-item active&quot;]/ul[@class=&quot;metismenu-container visible&quot;]/li[@class=&quot;metismenu-item active&quot;]/ul[@class=&quot;metismenu-container visible&quot;]/li[@class=&quot;metismenu-item active&quot;]/a[@class=&quot;metismenu-link active&quot;]</value>
      <webElementGuid>9096f9f6-362c-48ba-87a4-e85133f32bfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/nav/div/div/ul/li[2]/ul/li/ul/li/a</value>
      <webElementGuid>47e43be1-35c5-410a-9f40-1551aadd09ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalog'])[1]/following::a[1]</value>
      <webElementGuid>7808c468-929a-4398-8344-dbfbe4889d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barang'])[1]/following::a[2]</value>
      <webElementGuid>3a41a5c8-f476-43bc-9399-50b8925b92aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[1]/preceding::a[1]</value>
      <webElementGuid>3ea8ec4a-f542-457a-96b6-1cbaba051574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/home/inventory/review')]</value>
      <webElementGuid>abddc64c-adc9-41c8-8d23-d98cfd0a201e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/ul/li/a</value>
      <webElementGuid>51e64039-b037-497f-bc83-1d8dbe16862e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/home/inventory/review' and (text() = 'In Review' or . = 'In Review')]</value>
      <webElementGuid>ec5539b9-465c-4971-a6ac-bce2914ea2a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
