<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Simpan</name>
   <tag></tag>
   <elementGuidId>20e45aa9-0fa3-431e-a722-7a0e2b3b44c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[3]/div/div[3]/div[4]/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ladda-button.btn.btn-primary.std-btn-width > span.ladda-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8378c4cb-a326-4921-92db-2ff0695d0379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ladda-label</value>
      <webElementGuid>68e5483f-f4a4-4205-91e5-edd81c295f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>182562bb-7268-4b3a-ab75-82961cd61512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;wrapper wrapper-content&quot;]/div[1]/div[@class=&quot;page-editor&quot;]/div[4]/div[@class=&quot;pull-right&quot;]/button[@class=&quot;ladda-button btn btn-primary std-btn-width&quot;]/span[@class=&quot;ladda-label&quot;]</value>
      <webElementGuid>9ba589a4-5b82-434a-a2fa-44e2ee79cab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[3]/div/div[3]/div[4]/div[2]/button/span</value>
      <webElementGuid>effc726c-441d-4aa9-a245-2af32b368960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktifitas'])[3]/following::span[1]</value>
      <webElementGuid>0f0c271b-55f2-47d7-8738-7210775fee66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lama Pembelian'])[1]/following::span[3]</value>
      <webElementGuid>060f2b2c-19f5-4026-aefe-94434bca2ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='version number.'])[1]/preceding::span[2]</value>
      <webElementGuid>cde1493e-a69e-469c-a43e-76ae224463a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>b7647353-fe41-40da-8de0-0ec64b38700c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/button/span</value>
      <webElementGuid>04af1e68-31bd-462c-b5ef-42efec7132f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>63049d23-c0b5-4dfe-94a6-ed9898e3cff7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
